name: bluecheck
description: BlueCheck uygulaması
publish_to: 'none' # Özel proje

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  cupertino_icons: ^1.0.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  nearby_connections: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.png

